### ISSUE TITLE
Missing rejection handling for a promise

### ISSUE THREAD

**Issue by Querijn** [Querijn/BottyMcBotface#30]
> Error: You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
> TypeError: Cannot read property 'options' of undefined
>     at item.request.gen.end (/home/pi/bot/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:69:74)
>     at then (/home/pi/bot/node_modules/snekfetch/src/index.js:218:21)
>     at process._tickDomainCallback (internal/process/next_tick.js:135:7)

Every once in a while we get the nice error message described above.. We need to find it and handle it correctly. It doesn't break anything as far as I know, but let's handle it before it shuts down Botty every time it happens.

**Comment by Querijn** [comment]
This is a Discord.js bug
